
// Login user
POST http://107.22.138.106:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email" : "longtam20015@gmail.com",
    "password": "hoaiphong"
}

# // Register user
# POST http://localhost:5000/api/auth/register HTTP/1.1
# content-type: application/json

# {
#     "firstName": "ho",
#     "lastName": "phong",
#     "fullName": "Hồ Hoài Phong",
#     "email" : "longtam20016@gmail.com",
#     "password": "password"
# }
